spring:
  application:
    name: onboarding-back

  config:
    import: optional:classpath:application-secrets.yml

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # ?? update? ??
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  jwt:
    secret_key: ${JWT_SECRET_KEY}
